.PHONY: clean All

All:
	@echo "----------Building project:[ wordle - Debug ]----------"
	@cd "C:\Users\rober\Downloads\C++\wordle" && "$(MAKE)" -f  "wordle.mk"
clean:
	@echo "----------Cleaning project:[ wordle - Debug ]----------"
	@cd "C:\Users\rober\Downloads\C++\wordle" && "$(MAKE)" -f  "wordle.mk" clean
